---

  - name: making relevant directory
    become: true
    become_user: ec2-user
    become_method: sudo
    file:
     path: "{{ item }}"
     state: directory
     mode: 0777
    with_items:
    - ~/mongo/monogdata
    - ~/mongo/monogLog

  - name: extract archive file into ~/mongo
    become: true
    become_user: ec2-user
    become_method: sudo
    unarchive:
      src: "{{ mongourl }}"
      dest: ~/mongo
      mode: 0777
      remote_src: yes    
     
  - name: insert/update configuration using a local file
    become_user: ec2-user
    blockinfile:
      block: "{{ lookup('file', '../files/bashrc.txt') }}"
      dest: "~/.bashrc"
      backup: yes
      marker: "# {mark} ANSIBLE MANAGED BLOCK "
      insertafter: "EOF"   


  